### ISSUE TITLE
Push images to the forked repo

### ISSUE THREAD

**Issue by sergelogvinov** [siderolabs/kubelet#85]
I did not find 'kres' documentation how to change it.
But it will be very convenient to redefine the destination repo in make stage

https://github.com/siderolabs/kubelet/blob/821dc3e45dab8debca14df3ef82c0ebaf00cf600/.github/workflows/ci.yaml#L84-L96

like: 

```yaml
       - name: push 
         if: startsWith(github.ref, 'refs/tags/') 
         env: 
           PUSH: "true" 
           USERNAME: ${{ github.repository_owner }} 
         run: | 
           make 
```
